# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.20.6
yarn_mappings=1.20.6+build.1
loader_version=0.15.11

# Mod Properties
mod_version=2.0.1
maven_group=com.github.Provismet
archives_base_name=combatplus-core
modid=combat-plus-core

# Dependencies
fabric_version=0.98.0+1.20.6
lilylib_version=1.1.3-mc1.20.6

# Publishing
github_repo = CombatPlus-Core
github_branch = 1.20.6
modrinth_id = NbKFMiE7
curseforge_id = 973671
version_start = 1.20.5
version_end = 1.20.6