# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21.5
yarn_mappings=1.21.5+build.1
loader_version=0.16.10

# Mod Properties
mod_version=4.0.0
maven_group=com.github.Provismet
archives_base_name=combatplus-core
modid=combat-plus-core

# Dependencies
fabric_version=0.119.6+1.21.5
lilylib_version=4.0.0-mc1.21.5

# Publishing
github_repo=CombatPlus-Core
github_branch=1.21.5
modrinth_id=NbKFMiE7
curseforge_id=973671
version_start=1.21.5
version_end=1.21.5