# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21
yarn_mappings=1.21+build.2
loader_version=0.15.11

# Mod Properties
mod_version=3.2.0
maven_group=com.github.Provismet
archives_base_name=combatplus-core
modid=combat-plus-core

# Dependencies
fabric_version=0.100.1+1.21
lilylib_version=1.3.1-mc1.21

# Publishing
github_repo = CombatPlus-Core
github_branch = 1.21
modrinth_id = NbKFMiE7
curseforge_id = 973671
version_start = 1.21
version_end = 1.21.1